### ISSUE TITLE
Review open issues in hubotio/hubot

### ISSUE THREAD

**Issue by xurizaemon** [hubot-new/hubot#2] opened 2023-04-05 20:16 UTC
Currently there are _lots_ of issues in https://github.com/hubotio/hubot/issues, and some of them are things we should keep on the radar, or may even find that work in @joeyguerra's work to date addresses.

I propose we:

1. Make a list of all those open issues (and PRs)
2. Triage them briefly and discard what's not obviously of value
3. Open issues for any that appear worthwhile

Now is a good time to do that; I think it could help preserve the value of information gathered in those issues / PRs, while it's still relevant.

If I paste the .md into this issue comment, I'll trigger a lot of notifications but people won't be able to edit it. Maybe this belongs in a wiki for now? IDK.

[issues-2023-04-06.md](https://github.com/hubot-new/hubot-b/files/11162939/issues-2023-04-06.md)

**Comment by xurizaemon** [comment] 2023-04-05 21:03
I'm not sure if "Discussions" are any more collaborative than issues, but I put it in a Discussion: https://github.com/hubot-new/hubot-b/discussions/3

**Comment by joh6nn** [comment] 2023-04-06 15:18
I'm onboard to help with this kind of stuff. I have limited JS knowledge, but I can help with things like reaching out to people who filed an issue and checking in with them to see if they can still reproduce it, etc.

**Comment by joeyguerra** [comment] 2023-04-21 02:59
Closing since we've gotten our first PR into the original repo.

**Closed by joeyguerra** 2023-04-21 02:59 UTC
Labels: help wanted
